### ISSUE TITLE
A swept zero is not proof of an implemented CV, and only the human output says so

### ISSUE THREAD

**Issue by kamilpajak** [kamilpajak/railctl#53]
## Problem

A sweep can record `value: 0` for a CV, and nothing a machine reads says whether that is an implemented CV holding zero or a CV the decoder does not implement answering zero. `docs/probe-results.md` names the ambiguity and says it cannot be settled by reading:

> That a CV which answered `0` is implemented at all. That is the ordinary silence-versus-zero ambiguity and it applies at every CV number, not only above 511 - it is not a property of the high range and no read can settle it.

The tool does say this — but only to a person. `_SWEEP_EXIT_NOTE` goes out through `result.say(...)`, which appends to `CommandResult.lines`, and `CommandResult.envelope()` publishes `schema`, `ok`, `command`, `exit_code`, `elapsed_ms`, `link`, `station`, `warnings` and the result body. **`lines` is not in the envelope.** So `--format json`, `--format ndjson` and `--out -` carry no statement of the ambiguity at all.

This is not a regression introduced by #52, and it is worth being precise about that. Before #52 the caveat rode along inside `_UNEXERCISED_REASON`, which reaches machines through `warnings` — but only on a sweep whose bound passes CV511 (`if bound > HIGHEST_EXERCISED_CV`). A POM sweep bounded at CV255 never carried it, before or after. #52 removed the clause because attributing a universal ambiguity to one range was the misstatement being fixed; what it exposed is that the ambiguity was never delivered to machines systematically, it just happened to ride on a range-scoped warning some of the time.

## Why it is not covered by the status vocabulary

`no_response` is fine and needs nothing: it says the CV did not answer, and no script can mistake that for a value. The gap is specifically the rows that DID answer with `0`. Those are recorded exactly like a CV that genuinely holds zero, because on this hardware they are indistinguishable — which is the point, and which is what nothing machine-readable currently says.

## Goal

A script reading a sweep should be able to learn, from the envelope alone, that a zero is not proof of an implemented CV. Same rule as everywhere else in this tool: the human rendering and the machine rendering carry the same facts.

## Options

1. **A warning on every sweep**, name something like `sweep.zero_is_not_proof`, fired regardless of bound and regardless of mode. Additive, uses machinery that already exists, and reaches JSON and NDJSON through `warnings`. Costs one more warning on every single sweep, which is noise for a caller that already knows.
2. **A field on the sweep result body**, e.g. a `caveats` array, so it is data rather than a warning. Cleaner semantically — this is a property of the document, not an event that happened — but it is a new published field, so it needs the schema treatment.
3. **Put it in the backup document itself**, next to `set` and `sweep_range`, so it travels with the file rather than only with the run that produced it. A consumer reading a saved backup months later has the same question and currently has no answer at all.
4. **Document it and stop.** Say in `railctl schema` and the README that a `0` in a swept file is not proof of an implemented CV.

## Recommendation

Option 3, possibly with 1. The question "is this zero real" is asked of the FILE, usually long after the run, and a run-scoped warning does not reach that reader at all. Putting it in the document is the only option that answers the person who actually has the question. Option 1 additionally covers the streaming consumer who never writes a file.

Whichever is chosen, `_SWEEP_EXIT_NOTE` should keep saying it on the human path — this is about adding a machine channel, not moving the statement.

## Links

- `src/railctl/cli/commands/backup.py` — `_SWEEP_EXIT_NOTE`, `_warn_unexercised`, `_plan_sweep`
- `src/railctl/cli/result.py` — `CommandResult.say`, `CommandResult.envelope`
- `docs/probe-results.md` — "A CV above 511 checked against a known value", section "What is still open"
- Found while reviewing #52; the review flagged it, the refutation pass judged it out of that issue's scope, and both were right.
